### ISSUE TITLE
Varnish 6.0.2 Support

### ISSUE THREAD

**Issue by philipseidel** [fgsch/libvmod-sqlite3#6]
I am unable to compile on Varnish 6.0.2.
[libvmod-sqlite3.txt](https://github.com/fgsch/libvmod-sqlite3/files/2727865/libvmod-sqlite3.txt)

**Comment by fgsch** [comment]
This VMOD only supports varnish 3 and 4 at the moment.

While I plan to support more recent version I want to change its interface and a few other things.
I will close this ticket for now and hopefully revamp this VMOD in the near future.
